# Generated by Django 2.1.7 on 2019-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tittle', models.CharField(max_length=60)),
                ('thumbnail', models.CharField(max_length=150)),
                ('price', models.IntegerField(max_length=50)),
                ('stock', models.IntegerField(max_length=50)),
                ('product_description', models.CharField(max_length=300)),
                ('upc', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_name', models.CharField(max_length=200)),
            ],
        ),
    ]
