# Generated by Django 2.1.7 on 2019-03-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190314_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='product_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='thumbnail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='books',
            name='tittle',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='books',
            name='upc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='url_name',
            field=models.URLField(default=''),
        ),
    ]
